### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by irudoy** [fiverr/statistician#8]
It throws when comparing two webpack-5 stats.

Obviously the problem in `chunkalyse` package, but seems like it's not maintained. And other issues may occur after fixing this one.

```
TypeError: Cannot read property 'reduce' of undefined
    at /.../.yarn/cache/chunkalyse-npm-0.5.3-853143bb41-56c74e2f5f.zip/node_modules/chunkalyse/index.js:44:15
    at Array.reduce (<anonymous>)
    at analyseChunks (/.../.yarn/cache/chunkalyse-npm-0.5.3-853143bb41-56c74e2f5f.zip/node_modules/chunkalyse/index.js:37:3)
    at module.exports (/.../.yarn/cache/chunkalyse-npm-0.5.3-853143bb41-56c74e2f5f.zip/node_modules/chunkalyse/index.js:19:10)
    at Array.map (<anonymous>)
    at bundles (/.../.yarn/cache/statistician-npm-0.5.7-4d025164e9-4020e114f0.zip/node_modules/statistician/programs/diff-summary/bundles/index.js:17:32)
    at module.exports (/.../.yarn/cache/statistician-npm-0.5.7-4d025164e9-4020e114f0.zip/node_modules/statistician/programs/diff-summary/index.js:15:30)
    at module.exports (/.../.yarn/cache/statistician-npm-0.5.7-4d025164e9-4020e114f0.zip/node_modules/statistician/programs/diff-summary/cli.js:10:54)
    at async /.../.yarn/cache/statistician-npm-0.5.7-4d025164e9-4020e114f0.zip/node_modules/statistician/cli.js:21:18
```

**Comment by floydjones1** [comment]
weird, I am not having this issue and I am using webpack 5. Here is my example repo https://github.com/floydjones1/bundle-benchmark-pr-example

You can follow my repo if you like
